---
- name: install common packages
  apt:
    name:
      - curl
      - ca-certificates
      - apt-transport-https
      - software-properties-common
      - gnupg2
      - unzip
    state: present
    update_cache: true