---
- name: config redis cache for magento
  shell: "bin/magento setup:config:set --cache-backend=redis --cache-backend-redis-server=127.0.0.1  --cache-backend-redis-db=0"
  args:
    chdir: "{{magento_path}}"
  become_user: "{{app_user}}"

- name: config session storage
  shell: "bin/magento setup:config:set --session-save=redis --session-save-redis-host=127.0.0.1 --session-save-redis-port=6379 --session-save-redis-db=2"
  args:
    chdir: "{{magento_path}}"
  become_user: "{{app_user}}"